#!/bin/bash

IFS=,
PSQL_PAGER=''


run_query () {

q="select
CASE_NUMBER,
CASE_STATUS,
EMPLOYER_NAME,
JOB_TITLE,
SOC_CODE,
FULL_TIME_POSITION,
BEGIN_DATE,
END_DATE,
TOTAL_WORKER_POSITIONS,
NEW_EMPLOYMENT,
CONTINUED_EMPLOYMENT,
NEW_CONCURRENT_EMPLOYMENT,
CHANGE_PREVIOUS_EMPLOYMENT,
CHANGE_EMPLOYER,
AMENDED_PETITION,
EMPLOYER_ADDRESS1,
EMPLOYER_ADDRESS2,
EMPLOYER_CITY,
EMPLOYER_STATE,
EMPLOYER_POC_LAST_NAME,
EMPLOYER_POC_FIRST_NAME,
EMPLOYER_POC_JOB_TITLE,
SECONDARY_ENTITY_BUSINESS_NAME,
WORKSITE_ADDRESS1,
WORKSITE_ADDRESS2,
WORKSITE_CITY,
WORKSITE_STATE,
H_1B_DEPENDENT,
WILLFUL_VIOLATOR,
PREVAILING_WAGE,
EMPLOYER_PHONE,
EMPLOYER_PHONE_EXT,
EMPLOYER_POC_PHONE,
EMPLOYER_POC_PHONE_EXT,
EMPLOYER_POC_EMAIL,
H_1B_DEPENDENT
from LCA_Disclosure_Data_2022To2026Q1

where
CASE_STATUS = 'Certified'
and H_1B_DEPENDENT != 'Yes'
and SOC_CODE ilike '15-12%'
and NEW_EMPLOYMENT > 0
and BEGIN_DATE > now()

order by 
END_DATE desc,
SECONDARY_ENTITY_BUSINESS_NAME,
EMPLOYER_NAME asc;"

/usr/local/pgsql/bin/psql -A -d lca_data -c "$q" > ../Jobs/New_H1B_Tech_Jobs.csv
/usr/local/pgsql/bin/psql -H -d lca_data -c "$q" > ../Jobs/New_H1B_Tech_Jobs.html
/usr/local/pgsql/bin/psql -x -d lca_data -c "$q" > ../Jobs/New_H1B_Tech_Jobs.txt

}

run_query
